# Generated by Django 5.0.7 on 2024-08-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.PositiveSmallIntegerField()),
                ('start_y', models.PositiveSmallIntegerField()),
                ('end_x', models.PositiveSmallIntegerField()),
                ('end_y', models.PositiveSmallIntegerField()),
                ('piece', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
